### ISSUE TITLE
No module named trill.ast

### ISSUE THREAD

**Issue by gregersn** [gregersn/Trill#16]
```
❯ trill d12
Traceback (most recent call last):
  File "/usr/local/bin/trill", line 5, in <module>
    from trill.main import app
  File "/usr/local/lib/python3.10/site-packages/trill/__init__.py", line 3, in <module>
    from .parser import Parser
  File "/usr/local/lib/python3.10/site-packages/trill/parser.py", line 5, in <module>
    from .ast import expression
ModuleNotFoundError: No module named 'trill.ast'
```

**Comment by gregersn** [comment]
Fixed in ad7b7f1
